name: env_tutorial
## Triggers the workflow on when there is a push, or 
## pull request on the main branch
on: [pull_request, push] 
env:
  ## Sets environment variable
  MY_KEY: ${{secrets.API_KEY}}
jobs:
  job1:
    ## The type of runner that the job will run on
    runs-on: ubuntu-latest 
    steps:
      - name: step 1
        ## Reference your environment variables
        if:  env.MY_KEY == 12389
      
        run: echo "The API key is this" 
